### ISSUE TITLE
Ломается загрузка параметров из autumn-properties.json из-за ошибки в либе json

### ISSUE THREAD

**Issue by pravets** [autumn-library/autumn#103]
При наличии в конфиге autumn-properties.json значений параметров с //, например url, ломается файл настроек, так как пакет json криво обрабатывает комментарии.

При этом судя по предложению @EvilBeaver в комментарии от 18 августа 2020 года в https://github.com/oscript-library/json/issues/10 объявить пакет json deprecated имеет смысл отвязаться от использования этого пакета.

**Comment by nixel2007** [comment]
Спасибо за репорт, звучит как бага в configor.

@sfaqer @Nivanchenko

**Comment by nixel2007** [comment]
Исправлено в 4.3.1
