### ISSUE TITLE
Параллельный запуск всех рогаток

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/autumn#25]
Сейчас, если в контексте зарегистрировано две рогатки, и первая повесит исполняющий поток (например, вечный цикл с ожиданием сообщения в tcp соединении в winow), вторая рогатка не выполнится.

Предложение - запускать все рогатки в независимых фоновых заданиях, а в управляющем потоке делать ожидание их завершения.

@Nivanchenko что думаешь?

**Comment by Nivanchenko** [comment]
Думаю что ок, но было бы хорошо этим управлять. Настройкой какой. А то там же отладка не работает в ФЗ.

**Comment by nixel2007** [comment]
Будь мужиком, дебажь через сообщить)))

**Comment by nixel2007** [comment]
Добавить новый желудь ОттягивательРогаток, в него инжектить массив рогаток и детальки для запуска рогаток в принципе и фонового запуска.
В аннотацию &рогатка добавить Прозвище("Рогатка"). В остальные вероятно тоже.

**Comment by Nivanchenko** [comment]
Мб &Жгут ?

**Comment by nixel2007** [comment]
Новая аннотация? Для чего?

**Comment by Nivanchenko** [comment]
> Новая аннотация? Для чего?

Для оттягивателя рогаток, предложил название жгут 😉

**Comment by nixel2007** [comment]
А) да вроде новый тип жёлудя не нужен. Просто хочу ввести понятие инфраструктурого жёлудя (scope в спринге)
