### ISSUE TITLE
Библиотека autumn-logos

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/autumn#29]
Подключатель logos, внедрение &Логгер с авторасчетом имени лога, конфигурация через autumn-properties

**Comment by nixel2007** [comment]
Идеи реализации:

1) отдельный напильник + завязь с блестяшками.

Минусы - Логгер не внедрить в конструктор.
Плюсы - управляемость, произвольные параметры

2) мета-аннотация над пластилином

Плюсы - автоматическое внедрение в поля, методы, конструктор, не нужен отдельный напильник
Минусы - непонятно, как передавать параметры из аннотации Логгер в напильник/механизм прилепляемых частиц. Можно попробовать расширить аннотацию &Пластилин, и добавить туда массив параметров, которые передавать в НайтиЖелудь в прилепляемых частицах. А при разворачивании аннотации &Логгер заполнять его по данным свойства и владельца свойства

**Comment by nixel2007** [comment]
Вопросы - как быть с тестами?

Неинициализированный Логгер будет стрелять в рантайме. Придётся запускать тесты исключительно через осень, о независимых компонентных юнит тестах можно забыть.

Если расширять пластилин, то ещё есть возможность прокидывать Логгер через конструктор, тогда и в тестах можно будет его мокать и кидать. Отдельный напильник принуждает к поднятию контекста, пускай и с переопределенными верховными жёлудями/завязями

**Comment by Nivanchenko** [comment]
Ну т.к. это либа для осени, я не вижу криминала в поднимании контекста осени. Зато точно будем знать как работает у пользователя.

**Comment by nixel2007** [comment]
> А т.к. это либа для осени, я не вижу криминала в поднимании контекста осени.

Я не про либу как таковую, а про конечный компонент. Внедрение через конструктор как раз хорошо тем, что позволяет в тестах работать с классом вне ioc-контейнера. Это быстрее, часто нужно меньше контекста конфигурить, с моками, опять же, попроще.

Но раз ты тоже за мета-аннотацию, давай думать, как это провернуть. В принципе, в аннотации могут быть повторяемые параметры. Но это в движке. Как на это осень отреагирует, я пока не знаю. А доработать прилепление частиц в целом кажется однострочной задачей.

**Comment by Nivanchenko** [comment]
Большими мазками я себе представлял так. Мета-аннотация над пластилином. Дуб, генерящий объект. И класс с настройками который с файла сосет конфиг. В нем всякие имена приложения, шаблон имени лога, дефолтные значения и т.д.

**Comment by nixel2007** [comment]
Лог в данном случае компанейский желудь, инстанцируемый через завязь?

**Comment by nixel2007** [comment]
По поводу префикса - надо подумать, как две разные либы-зависимости разделить по префиксам

**Comment by Nivanchenko** [comment]
> Лог в данном случае компанейский желудь, инстанцируемый через завязь?

Да, компанейский

**Comment by nixel2007** [comment]
Окей, допустим, в &пластилин мы добавляем параметр Блестяшка. По своей природе он повторяемый. Как это отразить в конструкторе аннотации?

**Comment by Nivanchenko** [comment]
Я так далеко не заходил. Но наверное как-то через &логгер(мойпараметр="мойлоггер")

**Comment by Nivanchenko** [comment]
Нужно MVP  собрать, и посмотрим где чего не хватает

**Comment by Nivanchenko** [comment]
кажется ишус решен =) https://github.com/autumn-library/autumn-logos пушнул в хаб
