### ISSUE TITLE
Не разворачивать аннотации до уровня &Аннотация

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/autumn#30]
Если на свойстве навешано много аннотаций, в развёрнутой таблице аннотаций остаётся много аннотаций &Аннотация.

Предложение - убрать автоматическое добавление аннотаций нижнего уровня в список подчинённых аннотаций.

Можно добавить глобальную настройку осени + настройку-параметр на уровне самой аннотации для управлением необходимости разворачивания.

**Comment by nixel2007** [comment]
Сделать разворачиватель желудей полноценным инфраструткурным желудем, который разрешить инстанцировать на инит фазе. Добавить деталек.

**Comment by nixel2007** [comment]
Фабрику возможно тоже ожелудить.

**Comment by Nivanchenko** [comment]
> Сделать разворачиватель желудей полноценным инфраструткурным желудем, который разрешить инстанцировать на инит фазе. Добавить деталек.

Можно будет из деталек прокидывать параметры аннотаций ? Интересно

**Comment by nixel2007** [comment]
> Можно будет из деталек прокидывать параметры аннотаций ? Интересно

Не, я про детальку необходимости разворота до уровня &Аннотация
