### ISSUE TITLE
&Порядок

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/autumn#35]
Сделать универсальный механизм упорядочивания желудей, который будет работать и в порядке напильников, и рогаток и получения желудей массивом.

Вероятно, стоит добавить новое поле в ОпределениеЖелудя

**Comment by nixel2007** [comment]
Параметр Порядок в аннотации напильник объявить устаревшим и ругаться при его использовании.

Либо просто дропнуть обратную совместимость.

**Comment by Nivanchenko** [comment]
> Параметр Порядок в аннотации напильник объявить устаревшим и ругаться при его использовании.
> 
> Либо просто дропнуть обратную совместимость.

Может, выпилить совсем? Чего легаси плодить
