### ISSUE TITLE
[Ошибка] Проблема с верховным желудем

### ISSUE THREAD

**Issue by Absolemus** [autumn-library/autumn#54]
Сообщение в чатике [раз](https://t.me/oscript_library/84356) [два](https://t.me/oscript_library/84357)

[Читайте продолжение в источнике...](https://github.com/autumn-library/autumn/files/11225007/default.zip)

Если закомментить РандомныйЖелудь в ВебСерверМодифицированный тогда сервер стартанет
По зависимостям, у меня стоят Осень 3.1.3 и Вино 0.4.0 скачанные с помощью opm

**Comment by nixel2007** [comment]
Воспроизводится ещё?

**Comment by Absolemus** [comment]
На выходных воспроизведу, отпишусь

**Comment by nixel2007** [comment]
Мяу?

**Comment by Absolemus** [comment]
Усе роботоет, збазиба
