### ISSUE TITLE
Ошибка: Не удалось получить определение Желудя по имени Желудя

### ISSUE THREAD

**Issue by badyanov** [autumn-library/autumn#82]
Помогите разобраться. Пытаюсь воспроизвести пример из документации (с проверяторами и обновляторами). Создал класс-желудь **"./Классы/ПроверяторУстановленныхВерсий.os"**. При запуске выдает вот такую ошибку:

`{Модуль D:\Soft\OneScript\lib\autumn\src\Классы\Поделка.os / Ошибка в строке: 60 / Не удалось получить определение Желудя по имени Желудя ПроверяторУстановленныхВерсий}`

Экспериментальным путем выяснил, что если добавить добавление желудя вручную:
`Приложение.ДобавитьЖелудь(Тип("ПроверяторУстановленныхВерсий"));`

Тогда все работает. **НО!** В документации написано, что ДобавитьЖелудь уже не нужен, и в самих примерах такой метод не вызывается. Что я делаю не так?

```
Версии установленных компонентов:
OScript Version: 1.8.4.5
autumn                 | 3.3.0  |
```

**Comment by nixel2007** [comment]
Добрый день. Вы смотрите документацию в мастер ветке от грядущей версии 4.0.0. Там эти методы действительно больше не используются. Для 3.3.0 нужно смотреть документацию из тега: https://github.com/autumn-library/autumn/tree/v3.3.0

4.0 выйдет очень скоро, осталось немного дополировать документацию и определиться с релизом OneScript

**Comment by nixel2007** [comment]
И на всякий случай - все примеры из справки являются фантазиями в момент написания документации, их никто не пробовал действительно запускать, не факт, чо они вообще компилируются :)
так что если встретите что-то нерабочее - буду благодарен за пулл реквесты с исправлением документации.
